[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd react-fractal-viewer && npm ci"
]

[phases.build]
cmds = [
  "cd react-fractal-viewer && npm run build"
]

[start]
cmd = "cd react-fractal-viewer && npm run server"
