[phases.setup]
nixPkgs = ["nodejs", "gnumake", "gcc", "pkg-config"]
aptPkgs = ["libglfw3-dev", "libglew-dev", "libcglm-dev", "mesa-common-dev", "libx11-dev", "libxrandr-dev", "libxi-dev", "libssl-dev"]

[phases.install]
cmds = [
  "cd react-fractal-viewer && npm ci"
]

[phases.build]
cmds = [
  "make clean || true",
  "make CC=gcc CXX=g++ FLAGS='-O3 -Wall -I./includes -I./libft -I./imgui -I./imgui/backends' GL_LIBS='-lGL -lGLEW -lglfw -lm' OPENSSL_LIB='-lssl -lcrypto'",
  "cd react-fractal-viewer && npm run build"
]

[start]
cmd = "cd react-fractal-viewer && npm run start:prod"
