[phases.setup]
nixPkgs = ["nodejs", "gnumake", "gcc", "pkg-config"]
aptPkgs = ["libglfw3-dev", "libglew-dev", "libcglm-dev", "mesa-common-dev", "libx11-dev", "libxrandr-dev", "libxi-dev", "libssl-dev"]

[phases.install]
cmds = [
  "cd react-fractal-viewer && npm ci"
]

[phases.build]
cmds = [
  "chmod +x build-linux.sh",
  "./build-linux.sh",
  "cd react-fractal-viewer && npm run build"
]

[start]
cmd = "cd react-fractal-viewer && npm run start:prod"
